# Generated by Django 3.1.2 on 2020-10-26 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(blank=True, max_length=20, null=True)),
                ('rtn', models.CharField(max_length=14)),
                ('numero', models.CharField(blank=True, max_length=9, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'CLIENTE'), (2, 'PROVEEDOR'), (3, 'VENDEDOR'), (4, 'SUPERVISOR'), (5, 'Admin')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre_usuario', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('identidad', models.CharField(max_length=13, unique=True)),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Maculino'), ('F', 'Femenino')], max_length=10, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(max_length=8)),
                ('cedula', models.CharField(max_length=13)),
                ('rtn', models.CharField(max_length=14)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.CharField(max_length=50)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('roles', models.ManyToManyField(to='sistemaInventarioApi.Roles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tSalida', models.CharField(choices=[('CREDITO', 'Credito'), ('CONTADO', 'Contado')], default='CONTADO', max_length=10)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=30)),
                ('imagen', models.ImageField(null=True, upload_to=None)),
                ('marca', models.CharField(max_length=50)),
                ('isv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombrePopular', models.CharField(max_length=50)),
                ('descripcionProducto', models.CharField(max_length=50)),
                ('tipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.tipoproducto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.producto')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precioCosto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.producto')),
                ('idProveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descipcion', models.CharField(max_length=50)),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('idDescuento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.descuento')),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.factura')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='sistemaInventarioApi.usuario'),
        ),
        migrations.AddField(
            model_name='factura',
            name='idVendedor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vendedor', to='sistemaInventarioApi.usuario'),
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precioCosto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numeroFactura', models.CharField(max_length=100)),
                ('tipoEntrada', models.CharField(choices=[('ENCURSO', 'EnCurso'), ('PAGADO', 'Pagado')], default='ENCURSO', max_length=10)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
