# Generated by Django 3.1.2 on 2020-10-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='tipoEntrada',
        ),
        migrations.AddField(
            model_name='entrada',
            name='estadoPedido',
            field=models.CharField(choices=[('E', 'En Curso'), ('P', 'Pagado')], max_length=10, null=True),
        ),
    ]
