# Generated by Django 3.1.2 on 2020-10-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0002_auto_20201026_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='tSalida',
        ),
        migrations.AddField(
            model_name='salida',
            name='tipoSalida',
            field=models.CharField(choices=[('CRE', 'Credito'), ('CON', 'Contado')], max_length=10, null=True),
        ),
    ]
