# Generated by Django 3.1.2 on 2020-11-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0003_auto_20201026_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CLIENTE'), (2, 'PROVEEDOR'), (3, 'VENDEDOR'), (4, 'SUPERVISOR'), (5, 'ADMIN')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='roles',
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.roles'),
            preserve_default=False,
        ),
    ]
