# Generated by Django 3.1.2 on 2020-11-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0004_auto_20201121_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproducto',
            name='creacion',
        ),
        migrations.RemoveField(
            model_name='tipoproducto',
            name='ultima_modificacion',
        ),
    ]
