# Generated by Django 3.1.2 on 2020-11-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0005_auto_20201122_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproducto',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ABARROTERIA'), (2, 'REPUESTOS'), (3, 'COMIDA')], primary_key=True, serialize=False),
        ),
    ]
