# Generated by Django 3.1.2 on 2020-11-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0006_auto_20201122_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombrePopular',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
