# Generated by Django 3.1.2 on 2020-11-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0009_inventario_existencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estadoPedido',
            field=models.CharField(choices=[('E', 'En Curso'), ('P', 'Pagado')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='estadoPedido',
            field=models.CharField(choices=[('D', 'Devolucion'), ('C', 'Compra')], max_length=10, null=True),
        ),
    ]
