# Generated by Django 3.1.2 on 2020-12-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0010_auto_20201122_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='tipoProducto',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
