# Generated by Django 3.1.2 on 2020-12-10 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0012_auto_20201207_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cedula',
        ),
    ]
