# Generated by Django 3.1.2 on 2020-12-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0013_remove_usuario_cedula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_nacimiento',
            new_name='fechaNacimiento',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_admin',
            new_name='isAdmin',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuario',
            new_name='nombreUsuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='primer_nombre',
            new_name='primerNombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='segundo_apellido',
            new_name='segundoApellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='ultima_modificacion',
            new_name='ultimaModificacion',
        ),
    ]
