# Generated by Django 3.1.2 on 2020-12-11 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0014_auto_20201210_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='segundoApellido',
            new_name='apellido',
        ),
    ]
