# Generated by Django 3.1.2 on 2020-12-24 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0018_auto_20201216_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='precioCosto',
        ),
        migrations.AddField(
            model_name='entrada',
            name='inventario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.inventario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='numeroFactura',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
