# Generated by Django 3.1.2 on 2021-01-03 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaInventarioApi', '0020_auto_20210101_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sistemaInventarioApi.descuento'),
        ),
    ]
